# Generated by Django 3.1.2 on 2020-11-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.RemoveField(
            model_name='leave',
            name='created',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='updated',
        ),
    ]
